orbs:
  node: circleci/node@4.1.0

version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "STARTING TO BUILD"
      - run:
        name: Build
        command: yarn build
  test:
    docker:
      - image: cimg/node:15.2.1
    steps:
      - checkout
      - run: echo "STARTING TESTS"
      - run:
        name: Test
        command: yarn test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build