orbs:
  node: circleci/node@4.1.0

version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: cimg/node:15.2.1
    steps:
      - attach_workspace:
          at: .
      - run: npm run test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build